//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSSonarExtension.PackageImplementation.PckResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSSonarExtension.PackageImplementation.PckResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Succeed.
        /// </summary>
        internal static string AUTHOK {
            get {
                return ResourceManager.GetString("AUTHOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose CppCheck Executable.
        /// </summary>
        internal static string ChooseCppCheckMsg {
            get {
                return ResourceManager.GetString("ChooseCppCheckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Custom Tool Executable.
        /// </summary>
        internal static string ChooseCustomToolMsg {
            get {
                return ResourceManager.GetString("ChooseCustomToolMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Rats Executable.
        /// </summary>
        internal static string ChooseRatsMsg {
            get {
                return ResourceManager.GetString("ChooseRatsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Vera Executable.
        /// </summary>
        internal static string ChooseVeraMsg {
            get {
                return ResourceManager.GetString("ChooseVeraMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups something went was wrong, please report this exception: .
        /// </summary>
        internal static string ErrorMessageAutoAnalysis {
            get {
                return ResourceManager.GetString("ErrorMessageAutoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong: Cannot use extension: .
        /// </summary>
        internal static string EXCEPTIONWHILEAUTH {
            get {
                return ResourceManager.GetString("EXCEPTIONWHILEAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current File is Not Supported by Sonar Extension, Only C++ and C# are supported.
        /// </summary>
        internal static string FILELANGUANGENOTSUPPORTEDMSG {
            get {
                return ResourceManager.GetString("FILELANGUANGENOTSUPPORTEDMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar Settings are incorrect: Change at Tool &gt; Options &gt; Sonar Options.
        /// </summary>
        internal static string INCORRECTSONARSETTINGSMSG {
            get {
                return ResourceManager.GetString("INCORRECTSONARSETTINGSMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot proceed, key was not set correctly.
        /// </summary>
        internal static string KEYWASNOSETCORRECTLYMSG {
            get {
                return ResourceManager.GetString("KEYWASNOSETCORRECTLYMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar Host Not Set &gt; Tools &gt; Sonar &gt; General Options.
        /// </summary>
        internal static string MSGHOSTNOTSET {
            get {
                return ResourceManager.GetString("MSGHOSTNOTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar UserName Not Set &gt; Tools &gt; Sonar &gt; General Options.
        /// </summary>
        internal static string MSGUSERNAMENOTSET {
            get {
                return ResourceManager.GetString("MSGUSERNAMENOTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar UserPassword Not Set &gt; Tools &gt; Sonar &gt; General Options.
        /// </summary>
        internal static string MSGUSERPASSWORDNOTSET {
            get {
                return ResourceManager.GetString("MSGUSERPASSWORDNOTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralOptionsKey.
        /// </summary>
        internal static string PluginsOptionsModel_SelectedPluginItem_GeneralOptionsKey {
            get {
                return ResourceManager.GetString("PluginsOptionsModel_SelectedPluginItem_GeneralOptionsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Key Not Found or Invalid.
        /// </summary>
        internal static string REPOSITORYKEYINVALIDMSG {
            get {
                return ResourceManager.GetString("REPOSITORYKEYINVALIDMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Project Key [ex: Tekla:VSSonarPlugin].
        /// </summary>
        internal static string REQPROJKEYMSG {
            get {
                return ResourceManager.GetString("REQPROJKEYMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysed file does not exist in the defined project settings (Is this a test file), verify if the file exist in the defined project: .
        /// </summary>
        internal static string RESOURCEISINVALIDFORPROJECTKEY {
            get {
                return ResourceManager.GetString("RESOURCEISINVALIDFORPROJECTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Query used this Resource : .
        /// </summary>
        internal static string ResourceMsgWarning {
            get {
                return ResourceManager.GetString("ResourceMsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C#/ C++  solution needs to be open before running the analysis.
        /// </summary>
        internal static string SOLUTIONNOTOPENMSG {
            get {
                return ResourceManager.GetString("SOLUTIONNOTOPENMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension failed to load: VS will probably crash: .
        /// </summary>
        internal static string VSEXTENSIONFAILEDINIT {
            get {
                return ResourceManager.GetString("VSEXTENSIONFAILEDINIT", resourceCulture);
            }
        }
    }
}
